### ISSUE TITLE
savestates with Desmume 9.11

### ISSUE THREAD

**Issue by santosh-b** [SkyTemple/py-desmume#2]
It seems that the emulator gets corrupted whenever I load savestates generated by the standalone Desmume 9.11 version (and vice versa). Any fixes here? Thanks

This image whenever I upload a savestate generated by py-desmume into my standalone Desmume 9.11
![image](https://user-images.githubusercontent.com/43103834/92437118-d7a60d80-f16b-11ea-932f-2946bdbbfc9f.png)

When I do it the other way around, I get `There was an error loading the savestate` error.

I'm trying to switch between savestates because I need to use the standalone Desmume 9.11 for finding memory locations of interest. Obviously, this would be difficult to do in the python version because there's no disassembly/watch/etc. If there's an easy way to do it in python, that would also be great

**Comment by theCapypara** [comment]
The reason for this is that this version of DeSmuME is really old. So it's actually because I use more-or-less the newest version of DeSmuME and that doesn't support the old savestates anymore.

You have multiple options:
1. You can use the newest version of DeSmuME instead: https://ci.appveyor.com/project/zeromus/desmume/builds/34749987/artifacts
2. py-desmume can export memory and also watch memory (but there's no disassembly view).

- See https://py-desmume.readthedocs.io/en/latest/api_docs/desmume.emulator/memory_accessor.html for accessing memory and
- https://py-desmume.readthedocs.io/en/latest/api_docs/desmume.emulator/desmume_memory.html for the hooks (the `register_` methods)
